"""Generate the dealer/ops dashboard demo dataset from the real engines:
capacity scheduler output, crew scorecards on the tier rules, QC gate
status per active install, and the capacity forecast.

  python3 make_dashboard_data.py    writes website/dashboard/dashboard-data.js

Proprietary. (c) 2026 Ryan Brown / SightLine. All rights reserved.
"""
from __future__ import annotations

import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "econ"))
sys.path.insert(0, str(ROOT / "ops"))
sys.path.insert(0, str(ROOT / "sim" / "ops-sim"))
import capacity  # noqa: E402
import opssim  # noqa: E402
import throughput as tp  # noqa: E402

rng = random.Random(20260906)

CREW_NAMES = ["Wasatch Exteriors", "Timp Lighting Co", "Peak Season Crew",
              "Alpine Gutter + Light", "Provo Permanent", "Lehi Ladder Works"]


def crews():
    out = []
    for i, name in enumerate(CREW_NAMES):
        jobs = rng.randint(3, 90)
        first_pass = round(min(0.97, tp.qc_first_pass_at(min(jobs, 12))
                               + rng.uniform(-0.05, 0.02)), 2)
        avg_hr = round(tp.job_hours_at(min(jobs, 12)) + rng.uniform(-0.15, 0.45), 2)
        tier = "elite" if jobs > 60 and first_pass > 0.9 else "pro" if jobs > 20 else "certified"
        out.append({
            "id": f"crew-{i + 1}", "name": name, "tier": tier,
            "jobs_done": jobs,
            "avg_install_hr": avg_hr,
            "target_hr": tp.install_hours("new"),
            "qc_first_pass": round(first_pass, 2),
            "callback_90d": round(rng.uniform(0.0, 0.06), 3),
            "rating": round(rng.uniform(4.3, 5.0), 1),
            "home_base": [round(rng.uniform(0, 18), 1), round(rng.uniform(0, 18), 1)],
        })
    return out


def schedule(crew_rows):
    cap_crews = [capacity.Crew(id=c["id"], tier=c["tier"], rating=c["rating"],
                               home_base=tuple(c["home_base"]),
                               jobs_done=c["jobs_done"]) for c in crew_rows]
    jobs = [capacity.Job(id=f"job-{i + 1}",
                         site=(round(rng.uniform(0, 18), 1), round(rng.uniform(0, 18), 1)),
                         earliest_day=rng.randint(0, 4)) for i in range(34)]
    summary = capacity.schedule_jobs(cap_crews, jobs, horizon_days=6)
    sched = [{"job": j.id, "site": list(j.site), "crew": j.assigned,
              "day": j.day, "est_hours": j.est_hours}
             for j in jobs if j.assigned]
    return summary, sched


def qc_board(sched):
    gates = ["controller_wiring", "connector_clicked", "gasket_seated",
             "node_aim", "commissioning"]
    board = []
    for job in sched[:8]:
        done = rng.randint(0, len(gates))
        row = {"job": job["job"], "crew": job["crew"],
               "gates": [{"gate": g,
                          "status": "passed" if i < done else
                                    ("failed" if i == done and rng.random() < 0.25 else "pending")}
                         for i, g in enumerate(gates)]}
        board.append(row)
    return board


def main():
    crew_rows = crews()
    summary, sched = schedule(crew_rows)
    data = {
        "metro": "Utah County",
        "pipeline": {
            "quotes_open": 41, "jobs_booked": len(sched),
            "scheduled_this_week": sum(1 for s in sched if s["day"] <= 5),
            "unplaced": summary["unplaced"],
            "avg_est_hours": summary["avg_est_hours"],
        },
        "crews": crew_rows,
        "schedule": sched,
        "qc_board": qc_board(sched),
        "forecast": capacity.crews_needed(100),
        "opssim": opssim.simulate("new-metro-launch")["summary"],
        "tiers": {
            "certified": {"rev_share_plans_pct": 20, "priority": "standard queue"},
            "pro": {"rev_share_plans_pct": 25, "priority": "first refusal in home zip"},
            "elite": {"rev_share_plans_pct": 30, "priority": "metro-wide first refusal + demo homes"},
        },
        "all_estimates": True,
    }
    out = ROOT / "website" / "dashboard"
    out.mkdir(exist_ok=True)
    (out / "dashboard-data.js").write_text(
        "// generated by ops/make_dashboard_data.py; do not edit\n"
        "window.DASH = " + json.dumps(data) + ";\n")
    print("wrote", out / "dashboard-data.js",
          f"({len(crew_rows)} crews, {len(sched)} scheduled jobs)")


if __name__ == "__main__":
    main()
