"""One-page HTML reports per scenario, light theme.

  python3 report.py           writes reports/<scenario>.html for all three

Proprietary. (c) 2026 Ryan Brown / SightLine. All rights reserved.
"""
from __future__ import annotations

from pathlib import Path

import throughput as tp
import unit_economics as ue

OUT = Path(__file__).parent / "reports"

CSS = """
body{font-family:'IBM Plex Sans',system-ui,sans-serif;background:#FAF9F5;color:#1B2434;
margin:0;padding:34px;max-width:860px;margin:0 auto}
h1{font-family:'Chakra Petch',system-ui,sans-serif;letter-spacing:1px;font-size:26px}
h2{font-family:'Chakra Petch',system-ui,sans-serif;font-size:13px;letter-spacing:1.5px;
text-transform:uppercase;color:#C07A10;margin:26px 0 8px}
table{border-collapse:collapse;width:100%;background:#fff;border:1px solid #E4E1D8;border-radius:8px}
td,th{padding:8px 12px;border-bottom:1px solid #EEECE5;text-align:left;font-size:13.5px}
th{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#6E7480}
.big{font-family:'Chakra Petch',monospace;font-size:30px;font-weight:700}
.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}
.kpi{background:#fff;border:1px solid #E4E1D8;border-radius:10px;padding:14px}
.kpi .l{font-size:11px;color:#6E7480;text-transform:uppercase;letter-spacing:1px}
.good{color:#1E8A63}.bad{color:#C24545}
.note{font-size:12px;color:#6E7480;margin-top:20px}
"""


def _kpi(label, value, cls=""):
    return f'<div class="kpi"><div class="l">{label}</div><div class="big {cls}">{value}</div></div>'


def render(name: str) -> str:
    r = ue.run_scenario(name)
    sc, b, lt = r["scenario"], r["blended"], r["ltv"]
    inc = ue.incumbent_comparison()
    rows = "".join(
        f"<tr><td>{ch}</td><td>{int(w * 100)}%</td><td>${ue.CAC_CHANNELS[ch]['cac']:.0f}</td>"
        f"<td>{ue.CAC_CHANNELS[ch]['note']}</td></tr>"
        for ch, w in sc["channel_mix"].items())
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>SightLine econ: {name}</title><style>{CSS}</style></head><body>
<h1>SightLine unit economics: {name}</h1>
<p>{sc['description']}</p>
<h2>The four numbers</h2>
<div class="kpis">
{_kpi("Blended CAC", f"${r['cac']:.0f}", "good" if r['cac'] < 1000 else "bad")}
{_kpi("Marginal monitoring /mo", f"${b['marginal_cost_mo']:.2f}", "good" if b['marginal_cost_mo'] < 6 else "bad")}
{_kpi("Gross margin", f"{b['margin_pct']:.0f}%", "good" if b['margin_pct'] > 60 else "bad")}
{_kpi("LTV : CAC", f"{r['ltv_to_cac']:.1f}x", "good" if r['ltv_to_cac'] > 3 else "bad")}
</div>
<h2>Acquisition</h2>
<table><tr><th>Channel</th><th>Mix</th><th>CAC</th><th>Basis</th></tr>{rows}</table>
<p>Net CAC after hardware margin (${ue.HARDWARE_MARGIN_PER_INSTALL:.0f}/install est.):
<b>${lt['net_cac_after_hardware_margin']:.0f}</b>
{"(subscription payback: immediate)" if lt['payback_months_net'] == 0 else f"(net payback {lt['payback_months_net']} mo)"}.
Door-knock benchmark: ${inc['cac']['adt_net']:.0f} to ${inc['cac']['vivint_gross']:.0f}.</p>
<h2>Retention and value</h2>
<table>
<tr><th>Attrition</th><th>Lifetime</th><th>LTV (margin)</th><th>Subs at 36 mo</th><th>RMR</th><th>Portfolio at {r['portfolio_36mo']['multiple']:.0f}x</th></tr>
<tr><td>{sc['attrition'] * 100:.1f}%/yr (ADT actual: 13.1%)</td>
<td>{lt['lifetime_months']:.0f} mo</td><td>${lt['ltv_margin_usd']:,.0f}</td>
<td>{sc['subs_36mo']:,}</td><td>${r['portfolio_36mo']['rmr_usd_mo']:,.0f}/mo</td>
<td>${r['portfolio_36mo']['portfolio_value_usd']:,.0f}</td></tr>
</table>
<h2>Why incumbents cannot follow</h2>
<p style="font-size:13.5px">Their machine: ~${inc['cac']['adt_net']:.0f} door-knock CAC, human stations sold at $30 to $80/mo
(wholesale cost: ${inc['monitoring_cost_mo']['wholesale_station_actual']:.2f}), contracts to make the payback math survive,
and $7.4B of debt that eats the RMR. Guardian's marginal cost is ${b['marginal_cost_mo']:.2f}/home/mo and there are no contracts to defend.</p>
<div class="note">All prices and rates are estimates unless tied to a cited filing. Sources: ADT Q2 2026 filings, Vivint 2019 Form 425,
COPS SecureNet pricing, Barnes RMR multiples. Generated by econ/report.py; numbers come from unit_economics.py, never typed by hand.
Proprietary. (c) 2026 Ryan Brown / SightLine.</div>
</body></html>"""


def main():
    OUT.mkdir(exist_ok=True)
    for name in ue.SCENARIOS:
        (OUT / f"{name}.html").write_text(render(name))
        print("wrote", OUT / f"{name}.html")
    # throughput sidecar summary used by the strategy docs
    ie = tp.install_economics()
    (OUT / "throughput.html").write_text(f"""<!doctype html><html lang="en"><head>
<meta charset="utf-8"><title>SightLine throughput</title><style>{CSS}</style></head><body>
<h1>Install throughput: old model vs Ops Engine</h1>
<div class="kpis">
{_kpi("Old: crew day", f"{ie['old_model']['jobs_per_day']} install")}
{_kpi("New: crew day", f"{ie['new_model']['jobs_per_day']} installs", "good")}
{_kpi("Old cost/install", f"${ie['old_model']['cost_with_callbacks']:.0f}")}
{_kpi("New cost/install", f"${ie['new_model']['cost_with_callbacks']:.0f}", "good")}
</div>
<h2>Installer earnings (the recruiting pitch)</h2>
<p class="big good">${ie['installer_earnings']['margin_per_crew_day']:.0f}/day kept per crew</p>
<p>{ie['installer_earnings']['pitch']}</p>
<div class="note">Generated by econ/report.py from throughput.py. All estimates. Proprietary. (c) 2026 Ryan Brown / SightLine.</div>
</body></html>""")
    print("wrote", OUT / "throughput.html")


if __name__ == "__main__":
    main()
